#!/usr/bin/env bash

set -o errexit  # abort when any commands exits with error
set -o pipefail # abort when any command in a pipe exits with error
set -o nounset  # abort when any unset variable is used
set -f # prevent bash from expanding glob
trap 'echo "$0: line ${LINENO}: exiting because of error";exit 1' ERR

script_path="$(dirname $(realpath $0))"
 
: ${data_file:="${1:-"${script_path}/json_data/example.json"}"}
: ${template:="${2:-"${script_path}/dot_templates/example.j2.dot"}"}
: ${style:="${script_path}/json_data/styles.json"}

: ${render_file_name:="$(basename ${data_file}| sed 's/\.json$//g')"}
: ${render_folder:="${script_path}/rendering"}
: ${render_format:="png"}
: ${render_file:="${render_folder}/${render_file_name}.${render_format}"}

mkdir -p ${render_folder}
j2 -f json \
  ${template} \
  <( \
    cat ${data_file} \
    | jq --argjson styles "$(cat ${style})" \
    '.styles=($styles.styles * .styles)' \
  ) \
  | dot -T${render_format} -o ${render_file}

